<?php

add_filter('tdf/slugs', function () {
    return [
        'listing' => 'listing',
        'listings' => 'listings',
        'pagination' => 'pagination',
        'newest' => 'newest',
        'oldest' => 'oldest',
        'most_relevant' => 'most-relevant',
        'high_to_low' => 'high-to-low',
        'low_to_high' => 'low-to-high',
        '-from' => '-from',
        '-to' => '-to',
        'sw-lat' => 'sw-lat',
        'sw-lng' => 'sw-lng',
        'ne-lat' => 'ne-lat',
        'ne-lng' => 'ne-lng',
        'place-id' => 'place-id',
        'radius' => 'radius',
        'set-password' => 'set-password',
        'view' => 'view',
        'card' => 'card',
        'simple_card' => 'simple-card',
        'row' => 'row',
        'row_v2' => 'row-v2',
        'sort-by' => 'sort-by',
        'tab' => 'tab',
        'login' => 'login',
        'register' => 'register',
        'keyword' => 'keyword',
        'panel' => 'panel',
        'create' => 'create',
        'edit' => 'edit',
        'list' => 'list',
        'select_package' => 'select-package',
        'buy_package' => 'package',
        'my_packages' => 'my-packages',
        'settings' => 'settings',
        'moderation' => 'moderation',
        'messages' => 'messages',
        'favorites' => 'favorites',
        'user' => 'user',
        'promote' => 'promote',
        'extend' => 'extend',
        'bump_up' => 'bump-up',
        'my_orders' => 'my-orders',
        'orders' => 'orders',
        'verify_phone' => 'verify-phone',
        'set_phone' => 'set-phone',
        'email_confirmation' => 'email-confirmation',
        'name_asc' => 'name-asc',
        'select_subscription' => 'select-subscription',
        'select_subscription_success' => 'select-subscription-success',
        'select_subscription_cancel' => 'select-subscription-cancel',
        'subscription_canceled' => 'subscription-canceled',
        'update_payment_method_success' => 'update-payment-method-success',
        'update_payment_method_cancel' => 'update-payment-method-cancel',
        'users' => 'users',
    ];
});